# Generated by Django 5.0.1 on 2024-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='user_id')),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('CN', 'China'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('FR', 'France'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('KR', 'South Korea'), ('TW', 'Taiwan'), ('CH', 'Switzerland'), ('AU', 'Australia'), ('NL', 'Netherlands'), ('IR', 'Iran'), ('ZA', 'South Africa'), ('BR', 'Brazil'), ('SE', 'Sweden'), ('ES', 'Spain')], max_length=4)),
                ('subscription_type', models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], default='F', max_length=20)),
            ],
        ),
    ]
